name: CI
description: 'CI to build mac and windows version from master branch'
# this will help you specify where to run 
on:
  push:
    branches:
      - electron
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: electron
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: see directory in electron_dist
      run: ls ./electron
    # - name: add key to single keychain
    #   env: 
    #     MACOS_CERTIFICATE: ${{ secrets.MAC_CERT_P12 }}
    #     MACOS_CERTIFICATE_PWD: ${{ secrets.MAC_CERT_PWD }}
    #   run: |
    #   echo $MACOS_CERTIFICATE | base64 —decode > certificate.p12
    #   security import certificate.p12 -P ${{ secrets.MAC_CERT_PWD }}
    - name: electron mac os security identities
      run: security find-identity -v
    - name: Install dependencies
      run: yarn install
    - name: Build on MacOS
      env:
        ELECTRON: true
        APP_VERSION_NUMBER: 0.5.9
      run: yarn build
    - name: Build Electron
      env:
        ELECTRON: true
        CSC_KEY_PASSWORD: ${{ secrets.MAC_CERT_PWD }}
        APP_VERSION_NUMBER: 0.5.9
      run: yarn electron:buildUnix
    - name: see directory
      run: ls
    - name: check env
      run: echo $ELECTRON $FEATHERS_URL
    - name: see directory in electron_dist
      run: ls ./electron_dist
    - uses: rfcx/upload-to-release@master
      with:
        name: rfcx/uploader-app
        path: ./electron_dist
        action: unpublished
        release_id: 0.x.x
        release-repo: rfcx/uploader-app