name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@master
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@master
        with:
          node-version: 10.17.0
      - name: Prepare for app notarization
        if: startsWith(matrix.os, 'macos')
        # Import Apple API key for app notarization on macOS
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.API_KEY_ID }}.p8
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          mac_certs: ${{ secrets.MAC_CERT_P12 }}
          mac_certs_password: ${{ secrets.MAC_CERT_PWD }}
          windows_certs: ${{ secrets.WIN_CERT }}
          windows_certs_password: ${{ secrets.WIN_CERT_PWD }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          build_script_name: electron:build-github
          use_vue_cli: true
          max_attempts: 3
        env:
          APPLE_API_KEY_ID: ${{ secrets.API_KEY_ID }},
          APPLE_API_KEY_ISSUER_ID: ${{ secrets.API_KEY_ISSUER_ID }}
